version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    volumes:
      - ../bin/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_USER: osmocode
      MONGO_INITDB_PWD: password
      MONGO_INITDB_DATABASE: osmocode
      MONGO_DATABASE: osmocode
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: osmocode
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - 8081:8081
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_configdb:
  mongo_db:
